template_path: remote-templates/vpc.yaml
stack_name: it-services
parameters:
  VpcSubnetPrefix: "10.4"
  VpcName: it-services
hooks:
  before_update:
    - !cmd "curl https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/master/templates/vpc.yaml --create-dirs -o remote-templates/vpc.yaml"
