template_path: remote-templates/jumpcloud.yaml
stack_name: jumpcloud
dependencies:
  - essentials
parameters:
  LambdaBucket: essentials-awss3lambdaartifactsbucket-x29ftznj6pqw
  JcServiceApiKey: !ssm /infra/JcServiceApiKey
hooks:
  before_update:
    - !cmd "curl https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/master/templates/jumpcloud.yaml --create-dirs -o remote-templates/jumpcloud.yaml"
